"""Real ArmorPaint required. Run with:
    .venv\\Scripts\\python.exe -m pytest tests/test_inspect_project_integration.py -v
(needs AP_BINARY set to a working build -- see .env.example)
"""
import os

import pytest

from armorpaint_mcp.server import inspect_project

FIXTURE = os.path.join(os.path.dirname(__file__), "fixtures", "sample_project.arm")
FIXTURE_MULTI = os.path.join(os.path.dirname(__file__), "fixtures",
                             "sample_project_multi.arm")


@pytest.mark.integration
def test_inspect_project_reports_real_object_from_the_fixture():
    """Asserts specific, real content read from sample_project.arm -- not
    just types and truthiness. Before Finding 2's fix (server.py checking
    that `project` is an existing .arm file before launching ArmorPaint), a
    nonexistent project path made ArmorPaint silently fall back to its own
    default empty project, which reports ok:True with exactly one phantom
    object named "Tessellated" and empty materials/layers lists -- a shape
    the old, weaker version of this assertion could not distinguish from a
    real read of this fixture. These values were captured empirically by
    running (with Finding 2 already fixed, so a real check is meaningful):
        $env:AP_BINARY = "<...>\\ArmorPaint.exe"
        .venv\\Scripts\\python.exe -c "from armorpaint_mcp.server import
            inspect_project; print(inspect_project(project=r'tests\\fixtures\\
            sample_project.arm'))"
    sample_project.arm is generated by generate_fixture.py's
    script_project_new() with no custom material/layer building, so these
    are ArmorPaint's own project_new() defaults for this build:
        objects: one "Tessellated" object, location (0,0,0), size
            (1.039, 1.039, 1.039)
        materials: one "Material 1", node_count 2 (the default PBR node
            graph: base color feeding OUTPUT_MATERIAL_PBR)
        layers: one "Layer 1", resolution 2048, visible True, blending
            "Mix" (index 0 -- the default, unmodified layer blend mode)
    """
    result = inspect_project(project=FIXTURE)

    assert result["error"] is None, result["error"]
    assert result["ok"] is True

    assert len(result["objects"]) == 1
    obj = result["objects"][0]
    assert obj["name"] == "Tessellated"
    assert obj["location"] == [0.0, 0.0, 0.0]
    assert obj["size"] == [1.039, 1.039, 1.039]

    assert result["materials"] == [{"name": "Material 1", "node_count": 2}]

    assert result["layers"] == [{
        "name": "Layer 1",
        "resolution": 2048,
        "visible": True,
        "blending": "Mix",
    }]


@pytest.mark.integration
def test_inspect_project_reports_all_materials_in_a_multi_material_project():
    result = inspect_project(project=FIXTURE_MULTI)

    assert result["error"] is None, result["error"]
    assert result["ok"] is True
    assert len(result["materials"]) == 2
    names = [m["name"] for m in result["materials"]]
    assert len(set(names)) == 2  # two distinct materials, not the same one twice
